sonar.projectKey=${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}
sonar.projectName=${CI_PROJECT_TITLE}
sonar.projectVersion=${CI_COMMIT_TAG:-${CI_COMMIT_SHORT_SHA}}

sonar.sources=src
sonar.exclusions=**/build/**,**/third_party/**,**/test/**,**/vendor/**
sonar.sourceEncoding=UTF-8

sonar.cfamily.build-wrapper-output=bw-output
sonar.cfamily.compile-commands=bw-output/compile_commands.json
sonar.cfamily.threads=4
sonar.cfamily.cache.enabled=true
sonar.cfamily.cache.path=.sonar/cache

sonar.host.url=${SONAR_HOST_URL}
sonar.login=${SONAR_TOKEN}

sonar.links.scm=${CI_REPOSITORY_URL}
sonar.links.ci=${CI_PIPELINE_URL}

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=600

sonar.scm.provider=git
sonar.scm.forceReloadAll=true
